### ISSUE TITLE
day 1

### ISSUE THREAD

**Issue by briot** [johnperry-math/AoC2020#1]
You should likely use an Ada.Containers.Vectors to read the input in one go, instead of reading the file twice.

The 3-number case would fail with the following input:  20, 2000, 0    because of the extra "N+M<2020" you inserted. Don't know that it matters, of course, just something I noticed while looking at the code.

**Comment by johnperry-math** [comment]
Thank you! Based on Maxim's suggestion in the code I actually used Ada.Containers.Hashed_Sets, but I used your advice to read the input all at once.

My impression was that "expenses" should be positive. So I think there shouldn't be a case for 20, 2000, 0.

**Comment by johnperry-math** [comment]
Reading on another website I realize that hashed sets might not be the best idea, since repetition of data could be bad: 1010 + 1010 = 2020. I didn't encounter that problem myself, fortunately, so I'll go to vectors as you suggest.

**Comment by johnperry-math** [comment]
Latest version takes your advice on `<` versus `<=`, too.
